version: '3.8'

services:
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - bot_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - bot_network

volumes:
  redis_data:

networks:
  bot_network:
    driver: bridge 